image: docker:stable

before_script:
  - apt-get install -y -qq curl
  - curl -sL https://deb.nodesource.com/setup_9.x | sh -
  - apt-get update -qq
  - apt-get install -y -qq nodejs build-essential iproute2 git vim
  - nodejs -v

build:
  script:
    - docker run --cap-add=NET_ADMIN -p 3000:3000 --name cats -d chaos-workshop node main.js