image: gitlab/dind

stages:
  - build
  - deploy

build_docker_image:
  stage: build
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/sshankjha/chaos .
  - docker push registry.gitlab.com/sshankjha/chaos
  
deploy_stage:
  stage: deploy
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker pull registry.gitlab.com/sshankjha/chaos
  - docker run --cap-add=NET_ADMIN -p 3000:80 registry.gitlab.com/sshankjha/chaos node main.js